# Generated by Django 3.2 on 2024-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210511_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='code',
            field=models.URLField(null=True),
        ),
    ]
